Crash when trying to add click visit functionality.
Moved VisitViewHolder into VisitGroupAdapter to allow individual visit's
click listener to be set up. The click listener needs to be initialized in the
VisitGroupAdapter but used in onClick in VisitViewHolder.
Crashed on emulator becuase getAdapterPositon doesn't match the position parameter
in onItemClick.

Error was:
2020-06-28 16:13:40.692 15420-15420/com.michaelhsieh.placetracker E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.michaelhsieh.placetracker, PID: 15420
    java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.michaelhsieh.placetracker.DetailActivity.onItemClick(DetailActivity.java:155)
        at com.michaelhsieh.placetracker.VisitGroupAdapter$VisitViewHolder.onClick(VisitGroupAdapter.java:84)
        at android.view.View.performClick(View.java:6597)
        at android.view.View.performClickInternal(View.java:6574)
        at android.view.View.access$3100(View.java:778)
        at android.view.View$PerformClick.run(View.java:25885)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)